sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - cd gtest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../..
  - g++ -Igtest/googletest/include -Lgtest/build/googlemock/gtest/ -lgtest FizzBuzzTest.cpp -o FizzBuzzTest
  - ./FizzBuzzTest

notifications:
  email: false
