sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - cd gtest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ../..
  - g++ -I/usr/local/include -L/usr/local/lib -lgtest -lgtest ./FizzBuzzTest.cpp -o ./FizzBuzzTest.o
  - ./FizzBuzzTest.o

notifications:
  email: false
