sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - cd gtest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../..
  - g++ -Igtest/googletest/include/ -c main.cpp
  - g++ -pthread main.o  -Lgtest/build/googlemock/gtest/ -lgtest -o unit_tests.o
  - ./unit_tests.o

notifications:
  email: false
