sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - cd gtest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../..
  - g++ -Igtest/googletest/include/ -c FizzBuzzTest.cpp -o FizzBuzzTest.out
  - g++ -pthread FizzBuzzTest.out  -Lgtest/build/googlemock/gtest/ -lgtest
  - ./a.out

notifications:
  email: false
