sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - cd gtest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../..
  - $PWD
  - g++ -Igtest/googletest/include -Lgtest/build/googlemock/gtest/ -lgtest FizzBuzzTest.cpp -o FizzBuzzTest.o
  - ./FizzBuzzTest.o

notifications:
  email: false
